name: Deploy CIADI Plus Mobile Web

on:
  workflow_dispatch:
  push:
    branches:
      - ciadi-plus-build
    paths:
      - ciadi-plus-web/**
      - .github/workflows/deploy-ciadi-plus-web.yml

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: github-pages
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v5

      - name: Upload Mobile Web
        uses: actions/upload-pages-artifact@v4
        with:
          path: ciadi-plus-web

      - name: Deploy Mobile Web
        id: deployment
        uses: actions/deploy-pages@v4
